### ISSUE TITLE
Carla crash error

### ISSUE THREAD

**Issue by GiantSeaweed** [trust-ai/SafeBench#1]
Thank you for releasing this very interesting project!

I tried to run the code on Ubuntu20.04 with Nvidia RTX 3070 8G. 

I directly follow your instructions, but the Carla simulator always reports a crash error.

```
➜  SafeBench git:(main) sh run_docker.sh 
4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
sh: 1: xdg-user-dir: not found
../src/intel/isl/isl.c:2010: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
../src/intel/isl/isl.c:1994: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 8BPP textures with 3+ miplevels is disabled, but support for more levels is possible.
LowLevelFatalError [File:Unknown] [Line: 3762] 
Failed to link program [Program V_3AA5F7CCAD2B351344BE53DDA22E8BAEBA78720A_P_ABADFE631118A2CF0719C49D3F936DABF0CE8865]. Current total programs: 234, precompile: 0
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119 
Malloc Size=148816 LargeMemoryPoolOffset=279952 
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)
```

This is the output of your code:
```
......
process[scenario_node_ego_vehicle-1]: started with pid [2048]
process[gym_node_sac-1]: started with pid [2049]

pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
/home/carla/.local/lib/python3.8/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
[INFO] [1660536425.371128]: Connecting to Carla server...
[INFO] [1660536425.479813]: Carla server connected!
[INFO] [1660536427.033488]: Start generating scenarios for ego_vehicle using scenario_runner 0.9.11
Using data file: /home/carla/Evaluation/src/evaluation/scenario_node/data/standard.json
loading 80 data
creating testing records...
config 1/80
[INFO] [1660536427.741711]: Scenario status updated to ApplicationStatus.STARTING
============= load and wait for world
loading map Town05
```
I notice there are some related issues in Carla repo. 
I was wondering whether you also encountered similar errors.
Do you have any idea why this happens? Thanks!

By the way, I encounter 3 import error during the process, but they can be easily fixed and are not a big deal. 
```python
# src/agent/gym_node/src/planning/run.py
from planning.... # cannot find module planning

# src/agent/gym_node/src/planning/safe_rl/runner.py
import bullet_safety_gym
import safety_gym
```

**Comment by garyxcj** [comment]
Hi,

Sorry for the late reply. Thanks for your interest in our work!

I didn't meet this error before. It seems like an issue related to the CARLA simulator. I find that some of your error messages also appear in the issues in the CARLA repo. But there seems to be no solution. 

By the way, I updated the instructions in the README with more detailed steps to install the dependencies. It should work fine now. I tested it on Ubuntu20.04 with Intel i7-8700K and GeForce RTX 2080Ti. Sorry for the confusion.

Please let me know if you have further questions!

**Comment by wangchangquan** [comment]
I encounter the same error, have you solve the problem?

**Comment by garyxcj** [comment]
Can you provide more details on this issue? For example, can you successfully launch Carla using `sh run_docker.sh`? When will the Carla simulator crash?

**Comment by wangchangquan** [comment]
@GiantSeaweed @garyxcj 。   I change  a new computer with 2080ti,and run successful. I think the reason is the fomer graphics card’capacity is too low. Previously used a notebook had a 1065ti with 4GB.

**Comment by garyxcj** [comment]
Cool! However, it still seems like a driver problem. CARLA usually uses only 1GB of memory. If you want to find out the problem and run the platform on your previous computer, maybe you can check the difference between the drivers of the two computers. :)

**Comment by wangchangquan** [comment]
the os system and nvidia driver is the same. when I run the code  in the 2080ti,the nvidia-smi shows use more than 4GB memory , so I think is the memory is too low too run.
