### ISSUE TITLE
can you supply the inference code?

### ISSUE THREAD

**Issue by wangchangquan** [trust-ai/SafeBench#2]
1，Whether the reinforcement learning algorithm mentioned in the article needs to use the data generated by Safebench for training？
2，Can you provide inference code and pre training model ？such as DQN and DDPG

**Comment by garyxcj** [comment]
Hi,

Thank you for your interest in our work!

1. The RL models used in our paper are trained with data in SafeBench. However, you can test your models trained with any other data. They don't necessarily need to be trained with SafeBench.
2. You can download the models used in our paper [here](https://drive.google.com/drive/folders/1ONBoqMV6ngzn4szAIU1iLXRw9m8TT5UR?usp=sharing). We also updated the README. Please follow the instructions in step 4 to evaluate the models.

Please let me know if you have further questions!

**Comment by jingzhengli** [comment]
> Hi,
> 
> Thank you for your interest in our work!
> 
> 1. The RL models used in our paper are trained with data in SafeBench. However, you can test your models trained with any other data. They don't necessarily need to be trained with SafeBench.
> 2. You can download the models used in our paper [here](https://drive.google.com/drive/folders/1ONBoqMV6ngzn4szAIU1iLXRw9m8TT5UR?usp=sharing). We also updated the README. Please follow the instructions in step 4 to evaluate the models.
> 
> Please let me know if you have further questions!

How to load these .pt pre-trained model... It occurs error when "checkpoint = torch.load(f)"      ModuleNotFoundError: No module named 'planning'
