### ISSUE TITLE
cannot import name 'GetEgoVehicleRoute' from 'carla_ros_scenario_runner_types.srv' 

### ISSUE THREAD

**Issue by wangchangquan** [trust-ai/SafeBench#3]
in the site : https://github.com/trust-ai/SafeBench/tree/main/src/agent/gym_node/src/planning. we can find the source code of RL algrithm. but not describe the training method in details .I have some quesitons.
1,when i run "python run.py -p ppo",  encounter a problems，the error message is 

File "run.py", line 5, in <module>
    from planning.carla_runner import CarlaRunner
  File "/home/carla/Evaluation/src/agent/gym_node/src/planning/carla_runner.py", line 5, in <module>
    import gym_carla
  File "/home/carla/Evaluation/src/agent/gym_node/src/gym_carla/__init__.py", line 1, in <module>
    from .carla_env import CarlaEnv
  File "/home/carla/Evaluation/src/agent/gym_node/src/gym_carla/carla_env.py", line 22, in <module>
    from carla_ros_scenario_runner_types.srv import GetEgoVehicleRoute
ImportError: cannot import name 'GetEgoVehicleRoute' from 'carla_ros_scenario_runner_types.srv' (/home/carla/carla-ros-bridge/catkin_ws/devel/lib/python3/dist-packages/carla_ros_scenario_runner_types/srv/__init__.py)

I cannt find "GetEgoVehicleRoute'"  in the docker ,and the ros_brige official site (https://github.com/carla-simulator/ros-bridge) cannt find it either. so  where is the file ?

2,can you supply the training command and training dataset?
I think the  command "python run.py -p ppo",include training and evaluate ,is that right?  but where is the offline dataset . or we have to  collect data from carla server?

**Comment by garyxcj** [comment]
Hi, the RL algorithms are trained in SafeBench. We're working on the final release of the training API. The API will be provided before the SafeBench Challenge. Please stay tuned! Thank you!
